config/routes.rb
Mapper::Application.routes.draw do
  resources :zones

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  #Location type 0 -> railroads, type 1 -> accidents, type 2 -> schools
  attr_accessible :location, :location_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  def index
    render "index"
  end


  # POST /zones
  # POST /zones.json
  def create
    

    geofactory = RGeo::Cartesian.simple_factory(:srid => 4326)

    logger.debug params

    begin
      coordinates = RGeo::GeoJSON.decode(params["bounds"], :json_parser => :json)
    rescue
      render :json => {:success => false, :error => "Error in input format"}
      return
    end

    points = Array.new

    coordinates.each do |coordinate|
      points << coordinate.geometry
    end

    logger.debug geofactory.line_string(points)

    zones = Zone.where("ST_Intersects(location, box2d(ST_GeomFromText('#{geofactory.line_string(points)}')))")

    outpoints = Array.new

    zones.each do |zone|
      outpoints << zone.location
    end

    render :json => {:success => true, :points => RGeo::GeoJSON.encode(geofactory.multi_point(outpoints))}

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Maps JavaScript API v3 Example: Map Simple</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map_canvas {
        margin: 0;
        padding: 0;
        height: 100%;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=visualization"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://raw.github.com/JasonSanford/GeoJSON-to-Google-Maps/master/GeoJSON.js"></script>
    <script>
      var map;
      var points;
      var latlngArray = [];
      var heatmap;

      function getZones(){
          var bounds = map.getBounds();
          var content = '{"bounds" : { "type": "FeatureCollection","features": [{"type": "Feature","geometry": {"type": "Point", "coordinates": ['+bounds.getNorthEast().lng()+', '+bounds.getNorthEast().lat()+']}},{"type": "Feature","geometry": {"type": "Point", "coordinates": ['+bounds.getSouthWest().lng()+', '+bounds.getSouthWest().lat()+']}}]}}';
          $.ajax('/zones',{
            'data': content,
            'type': 'POST',
            'processData': false,
            'contentType': 'application/json' ,
            'success': function(data){
              console.log(data)
              points = GeoJSON(data.points)
              latlngArray = [];
              for(x in points){
                latlngArray.push(new google.maps.LatLng(points[x].position.lat(), points[x].position.lng()));
              }
              var pointArray = new google.maps.MVCArray(latlngArray);
              if (heatmap){
                heatmap.setMap(null);
              }
              heatmap = new google.maps.visualization.HeatmapLayer({
                data: pointArray,
                radius: 20
              });
              heatmap.setMap(map);
            }
          });
      }

      function initialize() {
        var mapOptions = {
          zoom: 13,
          center: new google.maps.LatLng(37.422304,-122.137846),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);
        google.maps.event.addListenerOnce(map, 'idle', function(){
          getZones();
        });
        google.maps.event.addListener(map, 'dragend', function() {
            getZones();
        });
        google.maps.event.addListener(map, 'zoom_changed', function() {
            getZones();
        });

        

      };

      

      $(function(){
          initialize();
        });

    </script>
  </head>
  <body>
    <div id="map_canvas"></div>
  </body>
</html>

app/views/zones/new.html.erb
<h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>